# Settings
baseurl = "https://gallery.blackpiratex.com"
languageCode = "en-us"
title = "Gallery By BlackPirateX"
theme = "autophugo"
#googleAnalytics = ""
#disableKinds = ["taxonomy", "term"]
#[taxonomies]
    tag = "tags"
  category = "categories"

[Author]
    name = "BlackPirateX"
    email = "contact@blackpiratex.com"

[params]
    # Meta
    description = "A photo Gallery By BlackPirateX"
    keywords = "gallery, photogallery, blackpiratex"
    #msvalidate = ""
    #googlesiteverification = ""
    thumb_width = 480
    thumb_quality = 50
    full_width = 960
    full_quality = 100
    column_count = 3
    #breadcrumb_use_title = false
    filename_as_phototitle = true
    images_downloadable = true
    images_downloadable_use_orig = false
    taxonomies_links = true

    # Headerbar links
    # Do not put too many links here,
    # it will break mobile appearance

    [[params.header.links]]
    name = "About"
    url = "#footer"
    icon = "fa-info-circle"

    # Footer panel

    [params.footer.paragraph]
    headline = "Gallery By BlackPirateX"
    text = "This is the place for me to keep all the nice pictures that I want to share with the world. ALl these images are taken by me. You can use these images for personal use. Visit my [website](https://blackpiratex.com)."

    [params.footer.social]
    headline = "Follow me"

    [[params.footer.social.links]]
    label = "Github"
    url = "https://github.com/blackpirateapps"
    icon = "fa-github"

    # Contact form

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'realEmail' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    [params.footer.contact]
    hide = true # Set this to true if you don't want to have a contact form on your site
    realEmail = "sudip@blackpiratex.com"
    headline = "Get in touch"
    buttonText = "Send"
    resetText = "Reset"

    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"

    # Copyright
    [params.footer.copyright]
    name = "BlackPirateX"
