baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Photo Gallery'
theme = 'modern-ui'



[caches]
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1 # Cache forever
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1 # Cache forever